{{- range .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: {{ .name }}-sa
      securityContext:
        runAsNonRoot: {{ $.Values.security.runAsNonRoot }}
        runAsUser: {{ $.Values.security.runAsUser }}
        runAsGroup: {{ $.Values.security.runAsGroup }}
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.registry }}/pm-{{ .name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .port }}
{{- end }}