{{- range .Values.microservices }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}-sa
  namespace: {{ $.Release.Namespace }}
automountServiceAccountToken: false # Hardens security by preventing the pod from querying the K8s API
{{- end }}